namespace MControl.Charts
{
    using System;

    //public static class ChartTypeComments
    //{
    //    public static string[] comments = new string[] { 
    //        "Bars - Standard bar graph; for each record the values a re evaluated and than a rectangle is Drawn to visualy show the value.", "Pie - Standard pie chart; this type of graph is used to visualy represent how large is a value compared to the whole sum.", "Bars3D - This type is an extension of the Bars type; The only difference is that instead of using rectangles as an element 3D bars are used.", "Donut - Standard donut chart; the only difference between a pie chart and a donut chart is the shape that is used. ", "Multibar - This type of graph is used to show the evoilution of multiple fileds of data on the same chart.", "Line - This is the standard line graph.", "MultiLine - A graph type that can be used to superimpose on the same graph multiple Line graphs.", "StackedBars - This type of graph can be used to show the evolution of a value, while still representing the components.", "StackedBarsFull - This graph is used to shaow the evolution of the inner structure of a value.        ", "StackedBars3D - 3-dimensional stacked bars. Good for showing the evolution of an agregated indicator and of its components.", "StackedBars3DFull - Good for showing the influence of the components on the agregated indicator.", "Multibars3D - No real difference between this type and Multibar, except for the 3D look; ", "Cylinders - This one is a bar type where the rectangles have been replaced with 3D cylinders.", "Pie3D - A standard 'Pie chart' with a 3D look. This type of graph has a very natural shadow, but has some limitations; for another 3D Pie chart graph you can try using Exploded3DPie with the \"explosion\" parameter set to 0.", "Surface - This one is an alternative to the Line chart. ", "MultiSurface - This one enables to superimpose multiple Surface graphs; it is important to use transparent colors, so that the surfaces underneath are still visible. ", 
    //        "Map - This type of graph Draws a map and visualy represents how big is an indicator for a region. The map is given by the user as an image (CustomImage property) and an xml file that describes the image (MapXML property).    ", "ExplodedPie - A Pie chart where the slices have been moved outwards.", "RadarLine - Radar graphs are great for showing data that has ciclic evolution (like the average montly temperature).  ", "RadarSurface - This one is RadarLine type of graph where surfaces are used instead of lines. ", "UserDrawnBars - This one is a standard bar graph where the rectangles are used with scaled copies of an image. The image is set with the CustomImage property.", "MultiRadarLine - RadarLine type of graph that permits superimposing multiple Sets of data.", "MultiRadarSurface - RadarSurface type of graph that permits superimposing multiple Sets of data.", "StackedRadarLine - This type can be used to show the evolution of a value and of the components it is made of.", "StackedRadarSurface - StackedRadarLine type of graph where colored surfaces are used instead of lines. ", "StackedSurface - This is used to show the evolution of a value while still showing the components that it is made of.", "FullStackedSurface - this graph type can be used to show the evolution of the structure(composition) of a value.", "Multi3DLine - This is a MultiLine graph where instead of using a line to represent values, a ribon-like surface is used. ", "MultiCurve - MultiCurve is MultiLine type of graph but instead of using lines to show the evolution from one period to another, curves are generated.", "Exploded3DPie - The 3D version of Exploded Pie. The slice movement can be controlled with the 'Explosion' Property.", "Exploded3DDonut - The 3D and 'exploded' version of the donut graph type. Both the size of the center area and the slice movement can be controlled.", "MapPoints - This mode Draws points on a map coresponding to the latitude / longitude. The DataItems must be Latitude, Longitude (in this order). The map is downloaded from a wms server that must be configurated with an xml file; see \"MapXML\" property. HowEver if MapXml is missing and there is a CustomImage that image will be used.", 
    //        "Bars3DWide - This type is an extension of the of Bars3D type; The only difference is that this type allows the bars to come as close as you want, while Bars3d will asure that there is enough space between the bars so that you can fully see the 3d part.", "StackedCylinders - This one is a Stacked bar type where the rectangles have been replaced with 3D cylinders.", "FullStackedCylinders - This one is a FullStacked bar type where the rectangles have been replaced with 3D cylinders.", "MultiCylinders - This one is a MultiBar type where the rectangles have been replaced with 3D cylinders.", "Surface3D - This one is a surface chart where the surface is replaced by a 3D paralleliped.", "MultiSurface3D - This one is a multi-surface chart where the surface is replaced by a 3D paralleliped.", "StackedSurface3D - This one is a stacked-surface chart where the surface is replaced by a 3D paralleliped."
    //     };

    //    public static string GetComment(int i)
    //    {
    //        return comments[i];
    //    }
    //}
}

